# basic
# ============================================================================
# if your site is serving on https://xxx.github.io, set `baseurl: /`
# if your site is serving on https://xxx.github.io/path, set `baseurl: /path`
baseurl: /book

# site title
title: Book

# site favicon, absolute path required
favicon: /assets/img/favicon.ico

# home button image, absolute path requried
avatar: /assets/img/avatar.jpg
# specify meaningful description for your avatar
avatarInfo: "Tokyo tower"

# default variables for post-type page
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true


# sass
# ============================================================================
sass:
  sass_dir: _sass
  style: compressed


# exclude none site related files
# ============================================================================
exclude:
  - README.md
  - LICENSE
  - github
  - package.json
  - package-lock.json
  - node_modules


# google analytics
# ============================================================================
# turn it off -> ga: false
ga: UA-69579248-1


# disqus
# ============================================================================
# turn it off for all posts -> disqus: false
# turn it off for a particular post -> add `comment: false` to post front matter
disqus: kkninjae
